name: flutter_demo_structure
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #localization
  # flutter_localizations:
  #   sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.8.7
  page_transition: ^2.1.0

  # core
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.6

  # navigation
  auto_route: ^8.3.0

  # storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  chewie: ^1.8.1

  # network
  http: ^1.1.2
  video_player: ^2.9.1
  dio: ^5.4.0
  reels_viewer: ^1.0.0+3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.3
  pretty_dio_logger: ^1.3.1

  # encryption
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # state management
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # common widget
  # use pub source until https://github.com/Baseflow/flutter_cached_network_image/pull/845 is merged
  # cached_network_image:
  #   git:
  #     url: https://github.com/Carapacik/flutter_cached_network_image.git
  #     path: cached_network_image

  form_field_validator: ^1.1.0
  country_pickers: ^3.0.1
  webview_flutter: ^4.4.4

  #device information
  device_info_plus: ^10.1.0

  flutter_secure_storage: ^9.0.0

  # document picker
  image_picker: ^1.0.7
  file_picker: ^8.0.6

  # sharing data
  url_launcher: ^6.2.3
  share_plus: ^9.0.0

  # ip address
  dart_ipify: ^1.1.1

  # permission handing
  permission_handler: ^11.1.0

  fluttertoast: ^8.2.4

  #social login
  twitter_login: ^4.4.2
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_web_auth: ^0.5.0
  font_awesome_flutter: ^10.7.0
  uuid: ^4.3.3
  flutter_facebook_auth: ^7.0.1
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  flutter_otp_text_field: ^1.1.3+2
  lottie: ^3.1.2
  flutter_swiper_null_safety: ^1.0.2
  readmore: ^3.0.0
  camerawesome: ^2.0.1
  open_file: ^3.3.2
  flutter_intl: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  mobx_codegen: ^2.6.1
# Your splash screen image for dark mode

  # Navigation generator
  auto_route_generator: ^8.1.0

  # API generator
  retrofit_generator: ^8.0.6

  # json parsing
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/image/
    - assets/icons/
    - assets/animate/
    - assets/image/logo_splash.png
    - assets/stikers/
    - assets/image/splash.jpg

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
    - family: figtree_black
      fonts:
        - asset: assets/fonts/Figtree-Black.ttf
    - family: figtree_medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf
    - family: figtree_bold
      fonts:
        - asset: assets/fonts/Karantina-Bold.ttf
    - family: figtree_semibold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf
    - family: figtree_extraBold
      fonts:
        - asset: assets/fonts/Figtree-ExtraBold.ttf
    - family: figtree_light
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf

flutter_intl:
  enabled: true
flutter_native_splash:
  image: assets/image/logo_splash.png
  background_image: assets/image/splash.jpg
  color: "#ffffff"
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/image/logo_splash.png
    background_image: assets/image/splash.jpg
    android_gravity: center
    ios_content_mode: center
  